unjs/c12

src/loader.ts
resolves #5, resolves https://github.com/nuxt/framework/issues/3518
Not sure if this is the correct fix or if we want jiti to have an option to force not using the native cache...
=> fix: disable `requireCache`

src/loader.ts
Currently using a package that injects an object as `theme` in nuxt.config and is broken since https://github.com/nuxt/framework/pull/7131. Obviously that will need to be fixed in the theme, but in a similar case in future it will be unclear what the issue is because it triggers the following error:
```js
Nuxi 3.0.0-rc.10-27706138.b31405f
Nuxt 3.0.0-rc.10-27706138.b31405f with Nitro 0.5.1-27706249.08ac81b
ERROR  Cannot start nuxt:  source.startsWith is not a function
at node_modules/.pnpm/c12@0.2.10/node_modules/c12/dist/index.mjs:174:44
at Array.some (<anonymous>)
at resolveConfig (node_modules/.pnpm/c12@0.2.10/node_modules/c12/dist/index.mjs:174:20)
at extendConfig (node_modules/.pnpm/c12@0.2.10/node_modules/c12/dist/index.mjs:151:27)
at extendConfig …
```
=> fix: validate sources value to be string

src/loader.ts
Example:
```ts
export default defineNuxtConfig({
extends: [
'@acme/component-lib/nuxt',
],
})
```
=> fix: allow extending from npm packages with subpath

README.md, src/loader.ts, test/fixture/package.json, test/index.test.ts
Issue: #29 
The only questions I have is 
1. Do we want to just normalize it to just use the `name` to drive how to load the package.json or do we want to support array of keys in addition of the `name`. The only reason I asked is unbuild supports these keys `unbuild` and `build`. Let me know what you think.
2. If we extend from multiple directories how do we want the `configFile` naming convention to be ?
Thanks 💚
=> feat: load config from `package.json`

src/loader.ts, test/fixture/base/config.ts, test/fixture/config.ts, test/index.test.ts
A New `$meta` config is supported for each configuration. This is mainly useful in conjunction with extended layers which can provide their metadata (such as name, version, etc).
Secondly, when extending a layer, users can provide custom source options `{ source: 'extend-source', options: {} }` or `source: ['extend-source, { ...options }]`. This is useful for defining options when extending a layer. Passing options such as cloning tokens. 
It is possible to override layer config and meta also using `opts.overrides` and `opts.meta` but it is probably for specific cases, such as multi-app support when we need to override a layer. we might not advocate this in general to users but gives an escape hatch to configure a layer meta itself by the consumer.
=> feat: layer meta and source options

.eslintrc, .github/workflows/ci.yml, package.json, pnpm-lock.yaml, src/dotenv.ts, src/index.ts, src/loader.ts, src/types.ts, test/index.test.ts, test/test.ts, test/types.ts, tsconfig.json
+ Refactor: Enabled strict type checks and CI tests
Support `<T, MT>` generics for all exported types. User config defined with `InputConfig<MyConfig, MyMeta>` can leverage built-in type hints for meta and environments.
New `createDefineConfig` and `DefineConfig` are also exposed for making it easier for frameworks exposing their `defineXConfig` type utils:
```ts
const defineMyConfig = createDefineConfig<MyConfig, MyMeta>();
```
=> feat: generic types support

src/loader.ts
https://github.com/nuxt/nuxt/issues/19882
New versions of node print:
```
ERROR  (node:11) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
```
=> fix: use `rm` instead of `rmdir` for recursive remove

README.md
=> docs: fix typo for `configFile`

src/loader.ts, test/fixture/.gitignore, test/fixture/_github/config.ts, test/fixture/_github/package.json, test/fixture/config.ts, test/index.test.ts
This PR improves extending behavior for GitHub layers by preferring to clone to local `node_modules/.c12/{id}`. This way layers can share the same dependencies of the main project.
Other improvements:
- Cloned layer names are explicitly hashed using ohash. This resolves issues when cloning from same github remote but different directories when it was possible to conflict cache
- Supported `gh:` shorthand
=> feat: improve extending github layers

README.md, src/loader.ts, src/types.ts, test/fixture/config.ts, test/index.test.ts
This PR allows setting giget cloning options both with top level `loadConfig` and also in each extends layer using layer meta:
```ts
export default defineConfig({
theme: "./theme",
extends: [
["gh:repo/ownwer", { giget: { auth: process.env.GITHUB_AUTH } }],
]
})
```
Also unblocks #51 since once we support this feature in giget, (https://github.com/unjs/giget/issues/6), `giget: { installDependencies: true }` would allow installing layer dependencies!
=> feat: allow setting giget clone options

src/loader.ts
As extension to https://github.com/unjs/c12/pull/109. When cloning a layer, it will be extracted to `node_modules/.c12/{name}` if `{cwd}/node_module` exists but the sub-layer, won't be because `node_modules/.c12/node_modules` does not! With this PR, sublayer will be clonned into parent `node_module/.c12`
=> fix: clone sub layers into `node_modules/.c12`

src/loader.ts, src/types.ts
#51
This adds a shortcut for `install` giget option. A layer extended with `[name, { install: true }]` will install it's dependencies
=> feat: support `install` for source options

src/loader.ts
If we take two RC files:
```
telemetry.consent=1
telemetry.seed=abc
telemetry.enabled=true
```
```
telemetry.consent=0
```
The current config returned is:
```ts
{
telemetry: {
consent: 0
}
}
```
With this fix, it will return:
```ts
{
telemetry: {
seed: 'abc',
enabled: true,
consent: 0
}
}
```
=> fix: deep merge rc sources with defu

src/loader.ts, src/types.ts, test/fixture/.config/test.ts, test/index.test.ts
This PR adds support for config sources (defaults, overrides, and user main config) to be also a (sync/async) function or promise.
Main initiative of this is to allow Nitro's default object infer user options (compatibilityDate) **before merge** but this feature generally should open new conventional usecases of async configs..
=> feat: resolvable configs

src/types.ts
=> fix(loadConfig): return type's `config` is not nullable

README.md, src/loader.ts, src/types.ts, test/loader.test.ts
resolves #180
When loading in user configs we don't always want to import remote non-trusted code in code-based config files (`.js`, `.ts`, ...). This PR adds the option to disable remote extending while still supporting extensions of local config files.
=> feat: allow disabling remote extend with `giget: false`

src/loader.ts
Previously it was impossible to get metadata for the main layer, meaning if you wanted to develop a layer with reference to its own metadata this was not available from the resolved config.
=> fix: preserve `meta` for main config

package.json, pnpm-lock.yaml, src/loader.ts, src/watch.ts
Upgrade to ohash v2.
Since it is ESM-only and c12 is not (yet!), we have to use dynamic imports.
`hash(path)` replaced with `digest(path).replace(-_, "").substring(0, 10)` to avoid breaking existing cache paths.
=> refactor: upgrade to ohash v2

src/loader.ts
=> fix: allow custom giget provider

src/dotenv.ts
resolves https://github.com/nuxt/nuxt/issues/31133
this checks whether `.env/` is a file before trying to read from it
=> fix: check if `.env/` is a file before accessing

src/loader.ts, src/types.ts
Context: Required by https://github.com/nitrojs/nitro/pull/3467
When sources like `overrides` or `defaults` are a custom function to extend from other sources, they might need access to not immediately resolved configs from other sources (as order matters, it wasn't needed for nitro case of `default` before `configs` had all resolved values while `overrides` needs it, we probably need to make a breaking behavior change to fix root cause later)
=> feat: pass raw configs to function sources

src/dotenv.ts, test/dotenv.test.ts
Hey :wave:
This PR makes `DotenvOptions.cwd` optional.
In case `dotenv` is enabled in `loadConfig`, it was defaulting to `options.cwd`.
In case `setupDotenv` or `loadDotenv` are used separately, it will now default to `process.cwd()`.
Thanks! :pray:
=> fix(loadDotenv): `cwd` is optional
